const friendss = [
  {
    id: 1,
    name:"Mahmoud Elshazly",
    img: "img/avatar-00.jpg",
    title:"sduyifgvbsuyhdvfbsudyhvbsuysdvsDV",
    time:"7.13",
    message:"30",
  },
  {
    id: 2,
    name:"Kamal Hosney",
    img: "img/avatar-01.png",
    title:"efdvlkjdbnfvju;bzdiujov;bdzikv;bdv",
    time:"4.18",
    message:"8",
  },
  {
    id: 3,
    name:"Chalipha Mo3tasem",
    img: "img/avatar-05.png",
    title:"sdaflkjvndfsv';bnvubdfvujdbvdjukz",
    time:"1.30",
    message:"15",
  },
  {
    id: 4,
    name:"Mostafa Rashad",
    img: "img/avatar-07.png",
    title:"sdsadjhasgdyfvgsaLvsavhbsdlvsai",
    time:"9.45",
    message:"40",
  },
  {
    id: 5,
    name:"Abdo Sikro",
    img: "img/avatar-04.png",
    title:"asdasdasdasdasdsadsadsadsadsadsd",
    time:"2.15",
    message:"22",
  },
  {
    id: 6,
    name:"Mohamed Gad",
    img: "img/avatar-02.png",
    title:"asdklgvns'hbvdiuozsdbviu;skdvb;sv",
    time:"4.05",
    message:"5",
  },
  {
    id: 7,
    name:"Tarek Shawki",
    img: "img/avatar-03.png",
    title:"aswdlkjsdzhfbv[iufdzsbvpsaibviwuybeviuwe",
    time:"7.13",
    message:"30",
  },





  {
    id: 7,
    name:"Tarek Shawki",
    img: "img/avatar-03.png",
    title:"aswdlkjsdzhfbv[iufdzsbvpsaibviwuybeviuwe",
    time:"7.13",
    message:"30",
  },
  {
    id: 7,
    name:"Tarek Shawki",
    img: "img/avatar-03.png",
    title:"aswdlkjsdzhfbv[iufdzsbvpsaibviwuybeviuwe",
    time:"7.13",
    message:"30",
  },
  {
    id: 7,
    name:"Tarek Shawki",
    img: "img/avatar-03.png",
    title:"aswdlkjsdzhfbv[iufdzsbvpsaibviwuybeviuwe",
    time:"7.13",
    message:"30",
  },
  {
    id: 7,
    name:"Tarek Shawki",
    img: "img/avatar-03.png",
    title:"aswdlkjsdzhfbv[iufdzsbvpsaibviwuybeviuwe",
    time:"7.13",
    message:"30",
  },
  {
    id: 7,
    name:"Tarek Shawki",
    img: "img/avatar-03.png",
    title:"aswdlkjsdzhfbv[iufdzsbvpsaibviwuybeviuwe",
    time:"7.13",
    message:"30",
  },
  {
    id: 7,
    name:"Tarek Shawki",
    img: "img/avatar-03.png",
    title:"aswdlkjsdzhfbv[iufdzsbvpsaibviwuybeviuwe",
    time:"7.13",
    message:"30",
  },
  {
    id: 7,
    name:"Tarek Shawki",
    img: "img/avatar-03.png",
    title:"aswdlkjsdzhfbv[iufdzsbvpsaibviwuybeviuwe",
    time:"7.13",
    message:"30",
  },
  {
    id: 7,
    name:"Tarek Shawki",
    img: "img/avatar-03.png",
    title:"aswdlkjsdzhfbv[iufdzsbvpsaibviwuybeviuwe",
    time:"7.13",
    message:"30",
  },
  
]